version: '3'
services: 
 db:
  image: icescrum/postgres
  container_name: icescrum_database
  environment: 
   - POSTGRES_PASSWORD=Silver99
  volumes: 
   - ./postgres:/var/lib/postgres/data
  networks: 
   -  icedatabase

 app:
  image: icescrum/icescrum
  container_name: icescrum
  volumes: 
   - ./app:/root
  networks: 
   - icedatabase


  